import type { ParsedSchema } from '@/lib/types'

function typeToDDL(sqlType: string): string {
  return sqlType.toUpperCase()
}

function columnToDDL(col: ParsedSchema['tables'][number]['columns'][number]): string {
  const parts = [`  ${col.name} ${typeToDDL(col.type)}`]
  if (col.primaryKey) parts.push('PRIMARY KEY')
  if (col.unique && !col.primaryKey) parts.push('UNIQUE')
  if (!col.nullable && !col.primaryKey) parts.push('NOT NULL')
  if (col.defaultValue !== null) parts.push(`DEFAULT ${col.defaultValue}`)
  return parts.join(' ')
}

export function generateDDL(schema: ParsedSchema): string {
  const lines: string[] = []
  lines.push('-- Generated by SchemaLens')
  lines.push(`-- ${schema.tables.length} tables, ${schema.relations.length} relations`)
  lines.push('')

  for (const table of schema.tables) {
    lines.push(`CREATE TABLE ${table.name} (`)
    const colDefs = table.columns.map(columnToDDL)
    lines.push(colDefs.join(',\n'))
    lines.push(');')
    lines.push('')
  }

  // FK ALTER statements
  for (const rel of schema.relations) {
    lines.push(
      `ALTER TABLE ${rel.fromTable} ADD CONSTRAINT ${rel.constraintName} ` +
      `FOREIGN KEY (${rel.fromColumn}) REFERENCES ${rel.toTable}(${rel.toColumn});`,
    )
  }

  return lines.join('\n')
}

function typeToReadable(sqlType: string): string {
  return sqlType
}

export function generateMarkdown(schema: ParsedSchema, schemaName: string, aiDocs: Record<string, string> | null): string {
  const lines: string[] = []
  lines.push(`# ${schemaName} Schema Documentation`)
  lines.push('')
  lines.push(`> Auto-generated by SchemaLens — ${schema.tables.length} tables, ${schema.relations.length} relationships`)
  lines.push('')
  lines.push('---')
  lines.push('')

  for (const table of schema.tables) {
    lines.push(`## ${table.name}`)
    if (aiDocs?.[table.name]) {
      lines.push('')
      lines.push(aiDocs[table.name])
    }
    lines.push('')
    if (table.rowEstimate !== null && table.rowEstimate > 0) {
      lines.push(`- **Est. rows:** ${table.rowEstimate.toLocaleString()}`)
    }
    lines.push('')

    // Columns table
    lines.push('| Column | Type | Nullable | Default | Constraints |')
    lines.push('|--------|------|----------|---------|-------------|')
    for (const col of table.columns) {
      const constraints = [
        col.primaryKey ? 'PK' : '',
        col.unique && !col.primaryKey ? 'UQ' : '',
      ].filter(Boolean).join(', ') || '—'
      lines.push(
        `| ${col.name} | ${typeToReadable(col.type)} | ${col.nullable ? 'YES' : 'NO'} | ${col.defaultValue ?? '—'} | ${constraints} |`,
      )
    }
    lines.push('')

    // FK relationships for this table
    const outgoing = schema.relations.filter(r => r.fromTable === table.name)
    if (outgoing.length > 0) {
      lines.push('**Foreign keys:**')
      for (const rel of outgoing) {
        lines.push(`- \`${rel.fromColumn}\` → ${rel.toTable}(\`${rel.toColumn}\`)`)
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated with SchemaLens — Interactive PostgreSQL Schema Explorer*')

  return lines.join('\n')
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function copyToClipboard(text: string) {
  return navigator.clipboard.writeText(text)
}
